name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: ghirahim_rs_build
    - name: Test
      run: cd ghirahim_rs_build && cargo test --verbose
    - name: Build
      run: cd ghirahim_rs_build && cargo build --verbose
